

######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    # post: '[btn.blog](/)'
    # wiki: '[btn.wiki](/wiki/)'
    # friends: '[友链](/friends/)'
    # about: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: Stellar 入门指南
      content: | # support markdown
        欢迎使用 [Stellar](https://github.com/xzMhehe/hexo-theme-stellar-codingce/) 主题，下面是您的入门指南，祝您使用愉快！
        <br>
        **第一步**
        创建 `blog/_config.stellar.yml` 文件，在此文件中填写需要自定义的主题配置。
        <br>
        **第二步**
        创建 `blog/source/_data/widgets.yml` 文件，此文件中填写需要自定义的侧边栏组件，例如 `welcome` 组件。
        <br>
        如果有任何疑问，请先查阅[文档](https://github.com/xzMhehe/hexo-theme-stellar-codingce)，如果文档中没有提供，请提 [issue](https://github.com/xzMhehe/hexo-theme-stellar-codingce/issues/) 向开发中询问。

menubar:
  columns: 4 
    # How many items in a row: 
    # You can add more according to your own needs, just meet the following format 
  items:
  - id: home # Highlighted menu_id in the page 
    theme: '#1BCDFC' # The color when highlighted is only valid when fill="currentColor" in svg 
    icon: solar:documents-bold-duotone # Supports svg/img tags, which can be defined in the icons.yml file, and also supports the URL of external images 
    title : Home # Title 
    url: / # Jump link, supports relative paths and absolute paths 
  - id: blogs 
    theme: '#3DC550' 
    icon: solar:notebook-bookmark-bold-duotone 
    title: Blogs 
    url: /blogs/ 
  - id: projects 
    theme: '#FA6400' 
    icon: solar:planet-bold-duotone 
    title: Explore 
    url: /projects/ 
  - id: about 
    theme: '#F44336' 
    icon: solar:chat-square-like-bold-duotone 
    title: about 
    url: /about/

article:
  share: [link]

style:
  border-radius:
    bar: 4px
    card: 4px
    block: 4px